name: doctests
on: [pull_request]
jobs:
  Doctest-annotations:
    runs-on: ubuntu-latest
    steps:
      - uses: ericphanson/julia-doctest@c65c98c5dae412bc38a1c5802e85d67d3b640fa8
        with:
          package: VisualStringDistances
  Doctest-suggestions:
    runs-on: ubuntu-latest
    steps:
      - uses: ericphanson/julia-doctest@c65c98c5dae412bc38a1c5802e85d67d3b640fa8
        with:
          package: VisualStringDistances
          filter_mode: 'diff_context'
