name: fix-doctests
on:
  pull_request:
    types: [ labeled ]
jobs:
  build:
    if: ${{ github.event.label.name == 'fix-doctests' }}
    runs-on: ubuntu-latest
    steps:
    - uses: julia-actions/setup-julia@latest
      with:
        version: 1.6.2
      
    - uses: actions/checkout@v2

    # Fix the doctests
    - name: Fix doctests
      uses: ericphanson/julia-doctest/run-doctests@c65c98c5dae412bc38a1c5802e85d67d3b640fa8
      with:
        package: VisualStringDistances
    # Commit the changes back
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Fix doctests
    # Remove the label
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: 'fix-doctests'
        github_token: ${{ secrets.GITHUB_TOKEN }}
